language: python

branches:
  only:
  - master

python:
    - 3.7

services:
    - docker

install:
    - pip install pelican markdown
    - pelican-themes -s $TRAVIS_BUILD_DIR/themes/Flex

notifications:
  email:
    on_success: always
    on_failure: always

script:
    - pelican -o output/
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - docker pull rcommande/blog
    - docker tag rcommande/blog rcommande/blog:previous
    - docker push rcommande/blog
    - docker build -t rcommande/blog $TRAVIS_BUILD_DIR
    - docker push rcommande/blog
