language: python

branches:
  only:
  - master

python:
    - 3.4

services:
    - docker

install:
    - pip install pelican
    - "ls -la"
    - pelican-themes -s $TRAVIS_BUILD_DIR/themes/Colourise11

notifications:
  email:
    on_success: always
    on_failure: always

script:
    - make html
    - docker build -t rcommande/blog $TRAVIS_BUILD_DIR
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push rcommande/blog
